from sqlalchemy import (BigInteger, Boolean, Column, Date, DateTime, Float,
                        ForeignKey, Integer, String, Text)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

from .common import CommonMixin

# 增强基本类
Base = declarative_base(cls=CommonMixin)


class ClassificationBom(Base):
    """分类编码"""
    分类名称 = Column(Text)
    分类编码 = Column(Text, primary_key=True, nullable=False)
    平台类别 = Column(Text, primary_key=True, nullable=False)


class Classification(Base):
    分类层级 = Column(Text, primary_key=True, nullable=False)
    证券代码 = Column(String(6), primary_key=True, nullable=False, index=True)
    证券简称 = Column(Text, nullable=False)
    分类名称 = Column(Text)
    分类编码 = Column(Text, nullable=False)
    平台类别 = Column(Text, nullable=False)


class ActualController(Base):
    """2.1 公司股东实际控制人"""
    __table_args__ = {'sqlite_autoincrement': True}

    序号 = Column(Integer, primary_key=True, autoincrement='auto')
    证券代码 = Column(String(6), nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    变动日期 = Column(DateTime, nullable=False)
    公告日期 = Column(DateTime, index=True)
    直接持有人ID = Column(Text)
    直接持有人名称 = Column(Text)
    实际控制人ID = Column(Text)
    实际控制人名称 = Column(Text)
    控股数量 = Column(BigInteger)
    控股比例 = Column(Float)
    控制类型编码 = Column(Text)
    控制类型 = Column(Text)
    直接控制人ID = Column(Text)
    直接控制人名称 = Column(Text)
    实际控制人类型 = Column(Text)


class CompanyShareChange(Base):
    """2.2 公司股本变动"""
    __tablename__ = 'company_share_changes'

    证券代码 = Column(String(6), primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, index=True)
    变动日期 = Column(DateTime, primary_key=True, nullable=False)
    变动原因编码 = Column(BigInteger)
    变动原因 = Column(Text)
    总股本 = Column(Float)
    未流通股份 = Column(Float)
    发起人股份 = Column(Float)
    国家持股 = Column(Float)
    国有法人持股 = Column(Float)
    境内法人持股 = Column(Float)
    境外法人持股 = Column(Float)
    自然人持股 = Column(Float)
    募集法人股 = Column(Float)
    内部职工股 = Column(Float)
    转配股 = Column(Float)
    其他流通受限股份 = Column(Float)
    优先股 = Column(Float)
    其他未流通股 = Column(Float)
    已流通股份 = Column(Float)
    人民币普通股 = Column(Float)
    境内上市外资股_B股 = Column(Float)
    境外上市外资股_H股 = Column(Float)
    高管股 = Column(Float)
    其他流通股 = Column(Float)
    流通受限股份 = Column(Float)
    配售法人股 = Column(Float)
    战略投资者持股 = Column(Float)
    证券投资基金持股 = Column(Float)
    一般法人持股 = Column(Float)
    国家持股_受限 = Column(Float)
    国有法人持股_受限 = Column(Float)
    其他内资持股_受限 = Column(Float)
    其中_境内法人持股 = Column(Float)
    其中_境内自然人持股 = Column(Float)
    外资持股_受限 = Column(Float)
    其中_境外法人持股 = Column(Float)
    其中_境外自然人持股 = Column(Float)
    其中_限售高管股 = Column(Float)
    其中_限售B股 = Column(Float)
    其中_限售H股 = Column(Float)
    最新记录标识 = Column(Integer)


class ExecutivesShareChange(Base):
    """2.3 上市公司高管持股变动"""
    __table_args__ = {'sqlite_autoincrement': True}

    序号 = Column(Integer, primary_key=True, autoincrement='auto')
    证券代码 = Column(String(6),
                  nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    截止日期 = Column(DateTime, nullable=False, index=True)
    公告日期 = Column(DateTime, nullable=False, index=True)
    变动人 = Column(Text, nullable=False, index=True)
    董监高姓名 = Column(Text)
    董监高职务 = Column(Text)
    变动人与董监高关系 = Column(Text)
    期初持股数量 = Column(Text)
    期末持股数量 = Column(Text)
    变动数量 = Column(Text)
    变动比例 = Column(Text)
    成交均价 = Column(Text)
    期末市值 = Column(Float)
    持股变动原因 = Column(Text)


class ShareholderShareChange(Base):
    """2.4 股东增（减）持情况"""
    __table_args__ = {'sqlite_autoincrement': True}
    序号 = Column(Integer, primary_key=True, index=True)

    证券代码 = Column(String(6), nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, nullable=False, index=True)
    增_减持截止日 = Column(DateTime, nullable=False)
    增_减持类型 = Column(Text, nullable=False)
    股东名称 = Column(Text, nullable=False)
    股东ID = Column(Text)
    变动数量 = Column(BigInteger)
    变动数量占总股本比例 = Column(Float)
    变动后占比 = Column(Float)
    增_减持价格上限 = Column(Text)


class ShareholdingConcentration(Base):
    """2.5 持股集中度"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    截止日期 = Column(DateTime, primary_key=True, nullable=False)
    股东总户数 = Column(Integer)
    A股户数 = Column(Integer)
    B股户数 = Column(Integer)
    H股户数 = Column(Integer)
    户均持股 = Column(Integer)
    户均持股比例 = Column(Float)
    前十大股东 = Column(Text)
    股东持股数量 = Column(BigInteger)
    股东持股比例 = Column(Float)
    股东持股比例比上报告期增减 = Column(Float)


class Quote(Base):
    """3.1 行情数据"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    交易日期 = Column(DateTime, primary_key=True, nullable=False)
    交易所 = Column(Text)
    今日开盘价 = Column(Float)
    最高成交价 = Column(Float)
    最低成交价 = Column(Float)
    收盘价 = Column(Float)
    成交数量 = Column(BigInteger)
    成交金额 = Column(Float)
    涨跌 = Column(Float)
    涨跌幅 = Column(Float)
    昨收盘价 = Column(Float)
    总笔数 = Column(Float)
    发行总股本 = Column(BigInteger)
    流通股本 = Column(BigInteger)
    市盈率 = Column(Float)
    换手率 = Column(Float)
    MA5 = Column(Float)
    MA10 = Column(Float)
    MA30 = Column(Float)
    MA120 = Column(Float)
    MA360 = Column(Float)
    本日融资余额 = Column(Float)
    本日融资买入额 = Column(Float)
    本日融资偿还额 = Column(Float)
    本日融券余量 = Column(Float)
    本日融券卖出量 = Column(Float)
    本日融券偿还量 = Column(Float)
    融券余量金额 = Column(Float)
    融资融券余额 = Column(Float)
    市盈率LYR = Column(Float)
    市盈率TTM = Column(Float)
    市盈率LYR_扣非 = Column(Float)
    市盈率TTM_扣非 = Column(Float)
    市净率LF = Column(Float)
    市销率LYR = Column(Float)
    市销率TTM = Column(Float)
    市现率LYR_经营 = Column(Float)
    市现率TTM_经营 = Column(Float)
    市现率LYR_总 = Column(Float)
    市现率TTM_总 = Column(Float)
    股息率LYR = Column(Float)
    股息率TTM = Column(Float)
    PEG = Column(Float)
    EV_EBITDA = Column(Float)


class InvestmentRating(Base):
    """4.1 投资评级"""
    __table_args__ = {'sqlite_autoincrement': True}

    序号 = Column(Integer, primary_key=True, index=True)
    证券代码 = Column(String(6), nullable=False, index=True)
    证券简称 = Column(String(10))
    发布日期 = Column(DateTime, nullable=False)
    研究机构简称 = Column(Text)
    研究员名称 = Column(Text)
    投资评级 = Column(Text)
    投资评级_经调整 = Column(Text)
    是否首次评级 = Column(Text)
    评级变化 = Column(Text)
    前一次投资评级 = Column(Text)
    目标价格_下限 = Column(Float)
    目标价格_上限 = Column(Float)


class PerformanceForecaste(Base):
    """5.1 上市公司业绩预告"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    公告日期 = Column(DateTime, primary_key=True, nullable=False, index=True)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    业绩类型编码 = Column(Integer)
    业绩类型 = Column(Text)
    业绩预告内容 = Column(Text)
    业绩变化原因 = Column(Text)
    报告期最新记录标识 = Column(Integer)
    本期净利润下限 = Column(Float)
    本期净利润上限 = Column(Float)
    本期净利润增减幅下限 = Column(Float)
    本期净利润增减幅上限 = Column(Float)


class Dividend(Base):
    """6.1 分红指标"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    分红年度 = Column(DateTime, primary_key=True, nullable=False)
    董事会预案公告日期 = Column(DateTime)
    董事会预案分红说明 = Column(Text)
    股东大会预案公告日期 = Column(DateTime)
    股东大会预案分红说明 = Column(Text)
    实施方案公告日期 = Column(DateTime)
    实施方案分红说明 = Column(Text)
    分配股本基数_实施 = Column(Float)
    股本基准年度 = Column(DateTime)
    送股比例 = Column(Float)
    转增比例 = Column(Float)
    派息比例_人民币 = Column(Float)
    派息比例_美元 = Column(Float)
    派息比例_港币 = Column(Float)
    送股数量 = Column(Float)
    转增数量 = Column(Float)
    派息金额_人民币 = Column(Float)
    A股股权登记日 = Column(DateTime)
    B股股权登记日 = Column(DateTime)
    A股除权日 = Column(DateTime)
    B股除权基准日 = Column(DateTime)
    B股最后交易日 = Column(DateTime)
    派息日_A = Column(DateTime)
    派息日_B = Column(DateTime)
    A股送红股到帐日 = Column(DateTime)
    A股新增股份上市日 = Column(DateTime)
    B股新增股份上市日 = Column(DateTime)
    送转前总股本 = Column(Float)
    送转后总股本 = Column(Float)
    送转前流通股本 = Column(Float)
    送转后流通股本 = Column(Float)
    分配股本基数_董 = Column(Float)
    分配股本基数 = Column(Float)
    方案进度 = Column(Text)
    取消分红公告日期 = Column(DateTime)
    A股转赠股份到帐日 = Column(DateTime)
    B股转赠股份到帐日 = Column(DateTime)
    B股送红股到帐日 = Column(DateTime)
    汇率 = Column(Float)


class AdditionalStockPlan(Base):
    """7.1 公司增发股票预案"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, primary_key=True, nullable=False, index=True)
    股票类别编码 = Column(BigInteger)
    股票类别 = Column(Text)
    每股面值 = Column(BigInteger)
    发行规模 = Column(Float)
    发行对象 = Column(Text)
    发行定价方式 = Column(Text)
    预计募资金额 = Column(Float)
    预计募资投向 = Column(Text)
    方案进度编码 = Column(BigInteger)
    方案进度 = Column(Text)
    股东决议公告日期 = Column(DateTime)
    增发获准公告日期 = Column(DateTime)
    变更说明 = Column(Text)
    发行价格 = Column(Text)
    发行方式 = Column(Text)
    股东决议有效期截止日 = Column(DateTime)
    方案状态 = Column(Text)
    终止公告日期 = Column(DateTime)
    记录标识 = Column(BigInteger, primary_key=True, nullable=False)


class AdditionalStockImplementation(Base):
    """7.2 公司增发股票实施方案"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, primary_key=True, index=True)
    股票类别编码 = Column(BigInteger)
    股票类别 = Column(Text)
    总发行数量 = Column(Float)
    公开发行数量 = Column(Float)
    每股面值 = Column(BigInteger)
    发行价格_人民币 = Column(Float)
    发行价格_外币 = Column(Text)
    币种编码 = Column(BigInteger)
    币种 = Column(Text)
    竞价上限 = Column(Float)
    竞价下限 = Column(Float)
    发行定价方式 = Column(Text)
    老股东配售方式 = Column(Text)
    老股东配售价格 = Column(Float)
    老股东配售比例 = Column(Float)
    加权发行市盈率 = Column(Float)
    摊薄发行市盈率 = Column(Float)
    发行前每股净资产 = Column(Float)
    发行后每股净资产 = Column(Float)
    预计募资金额 = Column(Float)
    实际募资总额 = Column(Float)
    其中现金 = Column(Float)
    实际募资净额_人民币 = Column(Float)
    实际募资净额_外币 = Column(Float)
    发行费用总额 = Column(Float)
    承销费用 = Column(Float)
    每股发行费用 = Column(Float)
    发行地区 = Column(Text)
    发行地区编码 = Column(Text)
    发行对象 = Column(Text)
    发行方式编码 = Column(BigInteger)
    发行方式 = Column(Text)
    承销方式编码 = Column(Text)
    承销方式 = Column(Text)
    分配承诺 = Column(Text)
    是否除权 = Column(BigInteger)
    股权登记日 = Column(DateTime)
    除权日 = Column(DateTime)
    发行前总股本 = Column(Float)
    发行后总股本 = Column(Float)
    发行前流通股本 = Column(Float)
    发行后流通股本 = Column(Float)
    网上发行日期 = Column(DateTime)
    网下询价配售开始日 = Column(DateTime)
    网下询价配售结束日 = Column(DateTime)
    其他发行日期 = Column(DateTime)
    网上申购上限 = Column(Float)
    申购代码1 = Column(Text)
    申购简称1 = Column(Text)
    申购代码2 = Column(Text)
    申购简称2 = Column(Text)
    网上发行中签率 = Column(Float)
    网下发行中签率 = Column(Float)
    起额认购倍数 = Column(Float)
    网上发行数量 = Column(Float)
    老股东配售数量 = Column(Float)
    网下配售数量 = Column(Float)
    承销余额 = Column(Float)
    回拨数量 = Column(Float)
    回拨方式编码 = Column(Text)
    回拨方式 = Column(Text)
    网上有效申购股数 = Column(Float)
    网上有效申购资金 = Column(Float)
    网上有效申购户数 = Column(Float)
    老股东有效申购股数 = Column(Float)
    老股东有效申购户数 = Column(Float)
    老股东有效申购资金 = Column(Float)
    网下有效申购户数 = Column(Float)
    网下有效申购股数 = Column(Float)
    网下有效申购资金 = Column(Float)
    一般法人申购数量 = Column(Float)
    一般法人配售数量 = Column(Float)
    一般法人配售户数 = Column(Float)
    证券基金申购数量 = Column(Float)
    证券基金配售数量 = Column(Float)
    证券基金配售户数 = Column(Float)
    战略投资者申购数量 = Column(Float)
    战略投资者配售数量 = Column(Float)
    战略投资者配售户数 = Column(Float)
    上市公告日期 = Column(DateTime)
    增发股上市日 = Column(DateTime)
    资金到帐日 = Column(DateTime)
    预计发行股数 = Column(Float)
    网上预设发行数量比例 = Column(Float)
    网下预设发行数量比例 = Column(Float)
    网上路演起始日 = Column(DateTime)
    招股意向书网址 = Column(Text)
    原股东优先申购日 = Column(DateTime)
    原股东最多认购数占发行数比例 = Column(Float)
    网下申购数量下限 = Column(Float)
    网下申购定金 = Column(Float)
    A类投资者网下申购中签比例 = Column(Text)
    B类投资者网下申购中签比例 = Column(Text)
    A类投资者网下申购单位 = Column(Text)
    B类投资者网下申购单位 = Column(Text)
    网下申购数量上限 = Column(Float)
    A类投资者认购下限 = Column(Float)
    B类投资者认购下限 = Column(Float)
    A类锁定期 = Column(Text)
    网下资金退缴日 = Column(DateTime)
    网上申购数量下限 = Column(Float)
    网上申购单位 = Column(Text)
    网上资金退款日 = Column(DateTime)
    网上中签结果公告日 = Column(DateTime)
    本次上市的无流通限制及锁定安排的股份 = Column(Text)
    发行后每股收益 = Column(Float)
    停牌截止日期 = Column(DateTime)
    停牌起始日期 = Column(DateTime)
    网下中签率公布及退款日 = Column(DateTime)
    网下申购定金到帐日 = Column(DateTime)
    记录标识 = Column(BigInteger, primary_key=True, index=True)


class SharePlacementPlan(Base):
    """7.3 公司配股预案"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, primary_key=True, nullable=False, index=True)
    股票类别编码 = Column(Integer)
    股票类别 = Column(Text)
    董事会预案内容 = Column(Text)
    股东大会预案内容 = Column(Text)
    配股比例_董 = Column(Float)
    配股比例 = Column(Float)
    每股面值 = Column(Integer)
    配股基准股本 = Column(Float)
    股本基准年度 = Column(DateTime)
    预计配股价格上限 = Column(Text)
    预计配股价格下限 = Column(Text)
    配股价格确定方式 = Column(Text)
    预计配股数量 = Column(Float)
    预计募集资金 = Column(BigInteger)
    预计募资投向 = Column(Text)
    方案进度编码 = Column(Integer)
    方案进度 = Column(Text)
    股东决议公告日期 = Column(DateTime)
    配股获准公告日期 = Column(DateTime)
    变更说明 = Column(Text)
    记录标识 = Column(BigInteger)


class SharePlacementImplementation(Base):
    """7.4 公司配股实施方案"""
    __table_args__ = {'sqlite_autoincrement': True}

    序号 = Column(Integer, primary_key=True, index=True)
    证券代码 = Column(String(6),nullable=False, index=True)
    证券简称 = Column(Text(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, nullable=False, index=True)
    股票类别编码 = Column(BigInteger)
    股票类别 = Column(Text)
    配股比例 = Column(Float)
    配股价格 = Column(Float)
    预计配股数量 = Column(Float)
    预计募集资金 = Column(Float)
    预计发行费用 = Column(Float)
    承销方式编码 = Column(BigInteger)
    承销方式 = Column(Text)
    股权登记日 = Column(DateTime)
    除权基准日 = Column(DateTime)
    配股缴款起始日 = Column(DateTime)
    配股缴款截止日 = Column(DateTime)
    实际配股数量 = Column(Float)
    承销余额 = Column(Float)
    实际募资总额 = Column(Float)
    实际募资净额 = Column(Float)
    发行费用总额 = Column(Float)
    承销费用 = Column(BigInteger)
    资金到账日 = Column(DateTime)
    配股前总股本 = Column(Float)
    配股后总股本 = Column(Float)
    配股前流通股本 = Column(Float)
    配股后流通股本 = Column(Float)
    国家股实配数量 = Column(Float)
    法人股实配数量 = Column(Float)
    职工股实配数量 = Column(Float)
    转配股实配数量 = Column(Float)
    其他股份实配数量 = Column(Float)
    公众股实配数量 = Column(Float)
    大股东认购数量 = Column(Float)
    大股东认购方式 = Column(Text)
    可转配股数量 = Column(Float)
    法人获转配数量 = Column(Float)
    公众获转配数量 = Column(Float)
    每股配权转让费 = Column(Float)
    公众配售代码 = Column(BigInteger)
    公众配售简称 = Column(Text)
    其他配售代码 = Column(Text)
    其他配售简称 = Column(Text)
    上市公告日期 = Column(DateTime)
    配股上市日 = Column(DateTime)
    配股权证交易起始日 = Column(DateTime)
    配股权证交易截止日 = Column(DateTime)
    配股失败_退还申购款日期 = Column(DateTime)
    停牌起始日 = Column(DateTime)
    停牌截止日 = Column(DateTime)
    配售对象 = Column(Text)
    发行方式 = Column(Text)
    配股发行结果公告日 = Column(DateTime)
    发行方式编码 = Column(Text)
    委托单位 = Column(Text)
    记录标识 = Column(BigInteger)


class IPO(Base):
    """7.5 公司首发股票"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    股票类别编码 = Column(BigInteger)
    股票类别 = Column(Text)
    总发行数量 = Column(Float)
    公开发行数量 = Column(Float)
    其中_国有股减持数量 = Column(Text)
    定向募集法人股 = Column(Text)
    定向募集职工股 = Column(Text)
    其他发行数量 = Column(Text)
    每股面值 = Column(BigInteger)
    发行价格_人民币 = Column(Float)
    发行价格_外币 = Column(Float)
    外币币种编码 = Column(Text)
    外币币种 = Column(Text)
    加权发行市盈率 = Column(Text)
    摊薄发行市盈率 = Column(Float)
    发行前每股净资产 = Column(Float)
    发行后每股净资产 = Column(Float)
    发行定价方式 = Column(Text)
    询价上限 = Column(Text)
    询价下限 = Column(Text)
    发行对象 = Column(Text)
    发行方式编码 = Column(Text)
    发行方式 = Column(Text)
    承销方式编码 = Column(Text)
    承销方式 = Column(Text)
    发行地区 = Column(Text)
    发行地区编码 = Column(Text)
    主要发起人 = Column(Text)
    分配承诺 = Column(Text)
    预计募集资金 = Column(Float)
    实际募资总额 = Column(Float)
    实际募资净额_人民币 = Column(Float)
    实际募资净额_外币 = Column(Float)
    发行费用总额 = Column(Float)
    承销费用 = Column(Float)
    每股发行费用 = Column(Float)
    招股公告日期 = Column(DateTime)
    市值计算日 = Column(DateTime)
    上网发行日期 = Column(DateTime)
    二级市场配售日期 = Column(DateTime)
    网下配售起始日 = Column(DateTime)
    网下配售截止日 = Column(DateTime)
    其他发行日期 = Column(DateTime)
    申购代码1 = Column(Text)
    申购简称1 = Column(Text)
    申购代码2 = Column(Text)
    申购简称2 = Column(Text)
    网上申购上限 = Column(BigInteger)
    上网发行数量 = Column(Text)
    二级市场配售数量 = Column(Text)
    网下配售数量 = Column(Text)
    回拨数量 = Column(Text)
    回拨方式编码 = Column(Text)
    回拨方式 = Column(Text)
    承销余额 = Column(Text)
    上网发行中签率 = Column(Float)
    二级市场配售发行中签率 = Column(Text)
    网下配售中签率 = Column(Text)
    超额认购倍数 = Column(Text)
    网上有效申购股数 = Column(Float)
    网上有效申购户数 = Column(Text)
    网上有效申购资金 = Column(Float)
    二级配售有效申购股数 = Column(Text)
    二级配售有效申购户数 = Column(Text)
    二级配售有效申购资金 = Column(Text)
    网下有效申购股数 = Column(Text)
    网下有效申购户数 = Column(Text)
    网下有效申购资金 = Column(Text)
    一般法人有效申购股数 = Column(Text)
    一般法人获配数量 = Column(Text)
    一般法人获配户数 = Column(Text)
    战略投资者有效申购股数 = Column(Text)
    战略投资者获配数量 = Column(Text)
    战略投资者获配户数 = Column(Text)
    证券基金有效申购数量 = Column(Text)
    证券基金获配数量 = Column(Text)
    证券基金获配户数 = Column(Text)
    上市公告日期 = Column(DateTime)
    资金到帐日 = Column(DateTime)
    战略投资者锁定期 = Column(Text)
    是否累计询价 = Column(Text)
    现场推介起始日 = Column(DateTime)
    现场推介截止日 = Column(DateTime)
    网上路演起始日 = Column(DateTime)
    申购价格范围 = Column(Text)
    初步询价开始日期 = Column(DateTime)
    初步询价截止日期 = Column(DateTime)
    发行价格区间公告日期 = Column(DateTime)
    网下冻结资金返还日期 = Column(DateTime)
    网上冻结资金返还日期 = Column(DateTime)
    定价公告日期 = Column(DateTime)
    网下投资者锁定期 = Column(Text)
    预计发行股数 = Column(Text)
    网上预设发行数量比例 = Column(Text)
    网下预设发行数量比例 = Column(Text)
    网上申购下限 = Column(Text)
    网下申购上限 = Column(Text)
    网下申购下限 = Column(Text)
    网下申购单位 = Column(Text)
    网上申购单位 = Column(Text)
    网下申购截止日 = Column(DateTime)
    招股意向书网址 = Column(Text)
    网上预设发行数量 = Column(Text)
    网下预设发行数量 = Column(Text)
    网下超额认购倍数 = Column(Text)
    战略投资者发行量比例 = Column(Text)
    摇号结果公告日 = Column(DateTime)
    中签率公告日 = Column(DateTime)
    是否行使超额配售权 = Column(Text)
    超额配售数量 = Column(Text)
    初步询价超额认购倍数 = Column(Text)
    预计新增发行数量上限 = Column(Text)
    预计老股东转让数量上限 = Column(Text)
    预计战略配售数量上限 = Column(Text)
    战略投资者配售数量 = Column(Text)
    老股东转让数量 = Column(Text)
    发行费用总额2 = Column(Text)
    老股东转让发行费用 = Column(Text)
    网下申购剔除比例 = Column(Text)
    网下申购剔除价格下限 = Column(Text)
    IPO阶段进展状态 = Column(Text)
    IPO阶段进展状态编码 = Column(Text)
    记录标识 = Column(Text)


class TtmIncomeStatement(Base):
    """8.1.1 个股TTM财务利润表"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    开始日期 = Column(DateTime)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(BigInteger)
    合并类型 = Column(Float)
    其中_营业收入 = Column(Float)
    其中_营业成本 = Column(Float)
    营业税金及附加 = Column(Float)
    销售费用 = Column(Float)
    管理费用 = Column(Float)
    堪探费用 = Column(Float)
    财务费用 = Column(Float)
    资产减值损失 = Column(Float)
    加_公允价值变动净收益 = Column(Float)
    投资收益 = Column(Float)
    其中_对联营企业和合营企业的投资收益 = Column(Float)
    影响营业利润的其他科目 = Column(Float)
    营业利润 = Column(Float)
    加_补贴收入 = Column(Float)
    营业外收入 = Column(Float)
    减_营业外支出 = Column(Float)
    其中_非流动资产处置损失 = Column(Float)
    加_影响利润总额的其他科目 = Column(Float)
    利润总额 = Column(Float)
    减_所得税 = Column(Float)
    加_影响净利润的其他科目 = Column(Float)
    净利润 = Column(Float)
    归属于母公司所有者的净利润 = Column(Float)
    少数股东损益 = Column(Float)
    每股收益 = Column(Float)
    基本每股收益 = Column(Float)
    利息收入 = Column(Float)
    已赚保费 = Column(Float)
    营业总收入 = Column(Float)
    营业总成本 = Column(Float)
    汇兑收益 = Column(Float)
    其他综合收益 = Column(Float)
    综合收益总额 = Column(Float)
    其中_归属于母公司 = Column(Float)
    其中_归属于少数股东 = Column(Float)
    手续费及佣金收入 = Column(Float)
    利息支出 = Column(Float)
    手续费及佣金支出 = Column(Float)
    退保金 = Column(Float)
    赔付支出净额 = Column(Float)
    提取保险合同准备金净额 = Column(Float)
    保单红利支出 = Column(Float)
    分保费用 = Column(Float)
    其中_非流动资产处置利得 = Column(Float)
    其他收益 = Column(Float)


class TtmCashFlowStatement(Base):
    """8.1.2 个股TTM现金流量表"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    开始日期 = Column(DateTime)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(Text)
    合并类型 = Column(Text)
    销售商品_提供劳务收到的现金 = Column(Float)
    收到的税费返还 = Column(Float)
    收到其他与经营活动有关的现金 = Column(Float)
    经营活动现金流入小计 = Column(Float)
    购买商品_接受劳务支付的现金 = Column(Float)
    支付给职工以及为职工支付的现金 = Column(Float)
    支付的各项税费 = Column(Float)
    支付其他与经营活动有关的现金 = Column(Float)
    经营活动现金流出小计 = Column(Float)
    经营活动产生的现金流量净额 = Column(Float)
    收回投资收到的现金 = Column(Float)
    取得投资收益收到的现金 = Column(Float)
    处置固定资产_无形资产和其他长期资产收回的现金净额 = Column(Float)
    处置子公司及其他营业单位收到的现金净额 = Column(Float)
    收到其他与投资活动有关的现金 = Column(Float)
    投资活动现金流入小计 = Column(Float)
    购建固定资产_无形资产和其他长期资产支付的现金 = Column(Float)
    投资支付的现金 = Column(Float)
    取得子公司及其他营业单位支付的现金净额 = Column(Float)
    支付其他与投资活动有关的现金 = Column(Float)
    投资活动现金流出小计 = Column(Float)
    投资活动产生的现金流量净额 = Column(Float)
    吸收投资收到的现金 = Column(Float)
    取得借款收到的现金 = Column(Float)
    收到其他与筹资活动有关的现金 = Column(Float)
    筹资活动现金流入小计 = Column(Float)
    偿还债务支付的现金 = Column(Float)
    分配股利_利润或偿付利息支付的现金 = Column(Float)
    支付其他与筹资活动有关的现金 = Column(Float)
    筹资活动现金流出小计 = Column(Float)
    筹资活动产生的现金流量净额 = Column(Float)
    汇率变动对现金的影响 = Column(Float)
    其他原因对现金的影响 = Column(Float)
    现金及现金等价物净增加额 = Column(Float)
    期初现金及现金等价物余额 = Column(Float)
    期末现金及现金等价物余额 = Column(Float)
    将净利润调节为经营活动现金流量 = Column(Float)
    净利润 = Column(Float)
    加_资产减值准备 = Column(Float)
    固定资产折旧_油气资产折耗_生产性生物资产折旧 = Column(Float)
    无形资产摊销 = Column(Float)
    长期待摊费用摊销 = Column(Float)
    处置固定资产_无形资产和其他长期资产的损失 = Column(Float)
    固定资产报废损失 = Column(Float)
    公允价值变动损失 = Column(Float)
    财务费用 = Column(Float)
    投资损失 = Column(Float)
    递延所得税资产减少 = Column(Float)
    递延所得税负债增加 = Column(Float)
    存货的减少 = Column(Float)
    经营性应收项目的减少 = Column(Float)
    经营性应付项目的增加 = Column(Float)
    其他 = Column(Float)
    经营活动产生的现金流量净额2 = Column(Float)
    不涉及现金收支的重大投资和筹资活动 = Column(Float)
    债务转为资本 = Column(Float)
    一年内到期的可转换公司债券 = Column(Float)
    融资租入固定资产 = Column(Float)
    现金及现金等价物净变动情况 = Column(Float)
    现金的期末余额 = Column(Float)
    减_现金的期初余额 = Column(Float)
    加_现金等价物的期末余额 = Column(Float)
    减_现金等价物的期初余额 = Column(Float)
    加_其他原因对现金的影响2 = Column(Float)
    现金及现金等价物净增加额2 = Column(Float)
    客户存款和同业存放款项净增加额 = Column(Float)
    向中央银行借款净增加额 = Column(Float)
    向其他金融机构拆入资金净增加额 = Column(Float)
    质押贷款净增加额 = Column(Float)
    发行债券收到的现金 = Column(Float)
    收到原保险合同保费取得的现金 = Column(Float)
    收到再保险业务现金净额 = Column(Float)
    保户储金及投资款净增加额 = Column(Float)
    处置以公允价值计量且其变动计入当期损益的金融资产净增加额 = Column(Float)
    收取利息_手续费及佣金的现金 = Column(Float)
    拆入资金净增加额 = Column(Float)
    回购业务资金净增加额 = Column(Float)
    客户贷款及垫款净增加额 = Column(Float)
    存放中央银行和同业款项净增加额 = Column(Float)
    支付原保险合同赔付款项的现金 = Column(Float)
    支付利息_手续费及佣金的现金 = Column(Float)
    支付保单红利的现金 = Column(Float)
    其中_子公司吸收少数股东投资收到的现金 = Column(Float)
    其中_子公司支付给少数股东的股利_利润 = Column(Float)
    投资性房地产的折旧及摊销 = Column(Float)


class QuarterlyIncomeStatement(Base):
    """8.2.1 个股单季财务利润表"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    开始日期 = Column(DateTime)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(BigInteger)
    合并类型 = Column(Text)
    其中_营业收入 = Column(Float)
    其中_营业成本 = Column(Float)
    营业税金及附加 = Column(Float)
    销售费用 = Column(Float)
    管理费用 = Column(Float)
    堪探费用 = Column(Float)
    财务费用 = Column(Float)
    资产减值损失 = Column(Float)
    加_公允价值变动净收益 = Column(Float)
    投资收益 = Column(Float)
    其中_对联营企业和合营企业的投资收益 = Column(Float)
    影响营业利润的其他科目 = Column(Float)
    营业利润 = Column(Float)
    加_补贴收入 = Column(Float)
    营业外收入 = Column(Float)
    减_营业外支出 = Column(Float)
    其中_非流动资产处置损失 = Column(Float)
    加_影响利润总额的其他科目 = Column(Float)
    利润总额 = Column(Float)
    减_所得税 = Column(Float)
    加_影响净利润的其他科目 = Column(Float)
    净利润 = Column(Float)
    归属于母公司所有者的净利润 = Column(Float)
    少数股东损益 = Column(Float)
    每股收益 = Column(Float)
    基本每股收益 = Column(Float)
    利息收入 = Column(Float)
    已赚保费 = Column(Float)
    营业总收入 = Column(Float)
    营业总成本 = Column(Float)
    汇兑收益 = Column(Float)
    其他综合收益 = Column(Float)
    综合收益总额 = Column(Float)
    其中_归属于母公司 = Column(Float)
    其中_归属于少数股东 = Column(Float)
    手续费及佣金收入 = Column(Float)
    利息支出 = Column(Float)
    手续费及佣金支出 = Column(Float)
    退保金 = Column(Float)
    赔付支出净额 = Column(Float)
    提取保险合同准备金净额 = Column(Float)
    保单红利支出 = Column(Float)
    分保费用 = Column(Float)
    其中_非流动资产处置利得 = Column(Float)
    其他收益 = Column(Float)


class QuarterlyCashFlowStatement(Base):
    """8.2.2 个股单季现金流量表"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    开始日期 = Column(DateTime)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(Float)
    合并类型 = Column(Text)
    销售商品_提供劳务收到的现金 = Column(Float)
    收到的税费返还 = Column(Float)
    收到其他与经营活动有关的现金 = Column(Float)
    经营活动现金流入小计 = Column(Float)
    购买商品_接受劳务支付的现金 = Column(Float)
    支付给职工以及为职工支付的现金 = Column(Float)
    支付的各项税费 = Column(Float)
    支付其他与经营活动有关的现金 = Column(Float)
    经营活动现金流出小计 = Column(Float)
    经营活动产生的现金流量净额 = Column(Float)
    收回投资收到的现金 = Column(Float)
    取得投资收益收到的现金 = Column(Float)
    处置固定资产_无形资产和其他长期资产收回的现金净额 = Column(Float)
    处置子公司及其他营业单位收到的现金净额 = Column(Float)
    收到其他与投资活动有关的现金 = Column(Float)
    投资活动现金流入小计 = Column(Float)
    购建固定资产_无形资产和其他长期资产支付的现金 = Column(Float)
    投资支付的现金 = Column(Float)
    取得子公司及其他营业单位支付的现金净额 = Column(Float)
    支付其他与投资活动有关的现金 = Column(Float)
    投资活动现金流出小计 = Column(Float)
    投资活动产生的现金流量净额 = Column(Float)
    吸收投资收到的现金 = Column(Float)
    取得借款收到的现金 = Column(Float)
    收到其他与筹资活动有关的现金 = Column(Float)
    筹资活动现金流入小计 = Column(Float)
    偿还债务支付的现金 = Column(Float)
    分配股利_利润或偿付利息支付的现金 = Column(Float)
    支付其他与筹资活动有关的现金 = Column(Float)
    筹资活动现金流出小计 = Column(Float)
    筹资活动产生的现金流量净额 = Column(Float)
    汇率变动对现金的影响 = Column(Float)
    其他原因对现金的影响 = Column(Float)
    现金及现金等价物净增加额 = Column(Float)
    期初现金及现金等价物余额 = Column(Float)
    期末现金及现金等价物余额 = Column(Float)
    将净利润调节为经营活动现金流量 = Column(Float)
    净利润 = Column(Float)
    加_资产减值准备 = Column(Float)
    固定资产折旧_油气资产折耗_生产性生物资产折旧 = Column(Float)
    无形资产摊销 = Column(Float)
    长期待摊费用摊销 = Column(Float)
    处置固定资产_无形资产和其他长期资产的损失 = Column(Float)
    固定资产报废损失 = Column(Float)
    公允价值变动损失 = Column(Float)
    财务费用 = Column(Float)
    投资损失 = Column(Float)
    递延所得税资产减少 = Column(Float)
    递延所得税负债增加 = Column(Float)
    存货的减少 = Column(Float)
    经营性应收项目的减少 = Column(Float)
    经营性应付项目的增加 = Column(Float)
    其他 = Column(Float)
    经营活动产生的现金流量净额2 = Column(Float)
    不涉及现金收支的重大投资和筹资活动 = Column(Float)
    债务转为资本 = Column(Float)
    一年内到期的可转换公司债券 = Column(Float)
    融资租入固定资产 = Column(Float)
    现金及现金等价物净变动情况 = Column(Float)
    现金的期末余额 = Column(Float)
    减_现金的期初余额 = Column(Float)
    加_现金等价物的期末余额 = Column(Float)
    减_现金等价物的期初余额 = Column(Float)
    加_其他原因对现金的影响2 = Column(Float)
    现金及现金等价物净增加额2 = Column(Float)
    客户存款和同业存放款项净增加额 = Column(Float)
    向中央银行借款净增加额 = Column(Float)
    向其他金融机构拆入资金净增加额 = Column(Float)
    质押贷款净增加额 = Column(Float)
    发行债券收到的现金 = Column(Float)
    收到原保险合同保费取得的现金 = Column(Float)
    收到再保险业务现金净额 = Column(Float)
    保户储金及投资款净增加额 = Column(Float)
    处置以公允价值计量且其变动计入当期损益的金融资产净增加额 = Column(Float)
    收取利息_手续费及佣金的现金 = Column(Float)
    拆入资金净增加额 = Column(Float)
    回购业务资金净增加额 = Column(Float)
    客户贷款及垫款净增加额 = Column(Float)
    存放中央银行和同业款项净增加额 = Column(Float)
    支付原保险合同赔付款项的现金 = Column(Float)
    支付利息_手续费及佣金的现金 = Column(Float)
    支付保单红利的现金 = Column(Float)
    其中_子公司吸收少数股东投资收到的现金 = Column(Float)
    其中_子公司支付给少数股东的股利_利润 = Column(Float)
    投资性房地产的折旧及摊销 = Column(Float)


class QuarterlyFinancialIndicator(Base):
    """8.2.3 个股单季财务指标"""

    证券代码 = Column(String(6),
                  primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    开始日期 = Column(DateTime)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(BigInteger)
    合并类型 = Column(Text)
    基本每股收益 = Column(Float)
    每股未分配利润 = Column(Float)
    营业利润率 = Column(Float)
    营业税金率 = Column(Float)
    营业成本率 = Column(Float)
    净资产收益率 = Column(Float)
    投资收益率 = Column(Float)
    总资产报酬率 = Column(Float)
    净利润率 = Column(Float)
    管理费用率 = Column(Float)
    财务费用率 = Column(Float)
    成本费用利润率 = Column(Float)
    三费比重 = Column(Float)
    应收账款周转率 = Column(Float)
    存货周转率 = Column(Float)
    运营资金周转率 = Column(Float)
    总资产周转率 = Column(Float)
    固定资产周转率 = Column(Float)
    应收账款周转天数 = Column(Float)
    存货周转天数 = Column(Float)
    流动资产周转率 = Column(Float)
    流动资产周转天数 = Column(Float)
    总资产周转天数 = Column(Float)
    股东权益周转率 = Column(Float)
    利息保障倍数 = Column(Float)
    营业收入增长率 = Column(Float)
    净利润增长率 = Column(Float)
    净资产增长率 = Column(Float)
    固定资产增长率 = Column(Float)
    总资产增长率 = Column(Float)
    投资收益增长率 = Column(Float)
    营业利润增长率 = Column(Float)
    每股现金流量 = Column(Float)
    每股经营现金流量 = Column(Float)
    经营净现金比率_短期债务 = Column(Float)
    经营净现金比率_全部债务 = Column(Float)
    经营活动现金净流量与净利润比率 = Column(Float)
    营业收入现金含量 = Column(Float)
    全部资产现金回收率 = Column(Float)
    毛利率 = Column(Float)
    期间费用率 = Column(Float)
    现金转换周期 = Column(Float)
    净利含金量 = Column(Float)
    期间费用增长率 = Column(Float)
    基本获利能力_EBIT = Column(Float)
    应收账款占比 = Column(Float)
    存货占比 = Column(Float)
    年化期间费用毛利比 = Column(Float)


class PeriodlyBalanceSheet(Base):
    """8.3.1 个股报告期资产负债表"""

    证券代码 = Column(String(6), primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, index=True)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(BigInteger)
    合并类型 = Column(Text)
    报表来源编码 = Column(BigInteger)
    报表来源 = Column(Text)
    货币资金 = Column(Float)
    结算备付金 = Column(Float)
    拆出资金 = Column(Float)   
    以公允价值计量且其变动计入当期损益的金融资产 = Column(Float)
    衍生金融资产 = Column(Float)
    应收票据 = Column(Float)
    应收账款 = Column(Float)
    预付款项 = Column(Float)
    应收保费 = Column(Float)
    应收分保账款 = Column(Float)
    应收分保合同准备金 = Column(Float)
    应收利息 = Column(Float)  
    应收股利 = Column(Float)
    其他应收款 = Column(Float)
    应收关联公司款 = Column(Float)
    买入返售金融资产 = Column(Float)   
    存货 = Column(Float)
    其中_消耗性生物资产 = Column(Float)
    划分为持有待售的资产 = Column(Float)
    发放贷款及垫款_流动资产 = Column(Float) 
    一年内到期的非流动资产 = Column(Float)
    交易性金融资产 = Column(Float)
    应收票据及应收账款 = Column(Float)
    合同资产 = Column(Float)   
    其他流动资产 = Column(Float)
    流动资产合计 = Column(Float)
    发放贷款及垫款_非流动资产 = Column(Float)
    可供出售金融资产 = Column(Float)
    持有至到期投资 = Column(Float)
    长期应收款 = Column(Float)
    长期股权投资 = Column(Float)
    投资性房地产 = Column(Float)
    固定资产 = Column(Float)   
    在建工程 = Column(Float)
    工程物资 = Column(Float)
    固定资产清理 = Column(Float)
    生产性生物资产 = Column(Float)
    油气资产 = Column(Float)
    无形资产 = Column(Float)
    开发支出 = Column(Float)
    商誉 = Column(Float)   
    长期待摊费用 = Column(Float)
    递延所得税资产 = Column(Float)
    债权投资 = Column(Float)
    其他债权投资 = Column(Float)
    其他权益工具投资 = Column(Float)
    其他非流动金融资产 = Column(Float)
    其他非流动资产 = Column(Float)   
    非流动资产合计 = Column(Float)
    资产总计 = Column(Float)  
    短期借款 = Column(Float)
    向中央银行借款 = Column(Float)
    吸收存款及同业存放 = Column(Float)
    拆入资金 = Column(Float)  
    以公允价值计量且其变动计入当期损益的金融负债 = Column(Float)
    衍生金融负债 = Column(Float)
    应付票据 = Column(Float)
    应付账款 = Column(Float)
    预收款项 = Column(Float)
    卖出回购金融资产款 = Column(Float)
    应付手续费及佣金 = Column(Float)
    应付职工薪酬 = Column(Float)
    应交税费 = Column(Float)
    应付利息 = Column(Float)
    应付股利 = Column(Float)
    其他应付款 = Column(Float)  
    应付关联公司款 = Column(Float)
    应付分保账款 = Column(Float)
    保险合同准备金 = Column(Float)
    代理买卖证券款 = Column(Float)
    代理承销证券款 = Column(Float)
    划分为持有待售的负债 = Column(Float)  
    一年内到期的非流动负债 = Column(Float)
    预计负债_流动负债 = Column(Float)
    递延收益_流动负债 = Column(Float)
    交易性金融负债1 = Column(Float)
    应付票据及应付账款 = Column(Float)
    合同负债 = Column(Float)   
    其他流动负债 = Column(Float)
    流动负债合计 = Column(Float)   
    长期借款 = Column(Float)
    应付债券 = Column(Float)
    其中_优先股_非流动负债 = Column(Float)
    永续债_非流动负债 = Column(Float)
    长期应付款 = Column(Float)
    长期应付职工薪酬 = Column(Float)
    专项应付款 = Column(Float)
    预计负债 = Column(Float)
    递延收益_非流动负债 = Column(Float)   
    递延所得税负债 = Column(Float)
    其他非流动负债 = Column(Float)
    非流动负债合计 = Column(Float)
    负债合计 = Column(Float)
    实收资本或股本 = Column(BigInteger)
    其他权益工具 = Column(Float)
    其中_优先股_所有者权益 = Column(Float)
    永续债_所有者权益 = Column(Float)
    资本公积 = Column(Float)
    减_库存股 = Column(Float)
    其他综合收益 = Column(Float)
    专项储备 = Column(Float)
    盈余公积 = Column(Float)
    一般风险准备 = Column(Float)
    未分配利润 = Column(Float)
    外币报表折算价差 = Column(Float)
    归属于母公司所有者权益 = Column(Float)
    少数股东权益 = Column(Float)
    非正常经营项目收益调整 = Column(Float)
    所有者权益或股东权益合计 = Column(Float)
    负债和所有者或股东权益合计 = Column(Float)
    备注 = Column(Text)


class PeriodlyIncomeStatement(Base):
    """8.3.2 个股报告期利润表"""

    证券代码 = Column(String(6), primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, index=True)
    开始日期 = Column(DateTime)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(BigInteger)
    合并类型 = Column(Text)
    报表来源编码 = Column(BigInteger)
    报表来源 = Column(Text)
    营业总收入 = Column(Float)
    其中_营业收入 = Column(Float)
    利息收入 = Column(Float)
    已赚保费 = Column(Float)
    手续费及佣金收入 = Column(Float)
    营业总成本 = Column(Float)
    其中_营业成本 = Column(Float)
    利息支出 = Column(Float)
    手续费及佣金支出 = Column(Float)
    退保金 = Column(Float)
    赔付支出净额 = Column(Float)
    提取保险合同准备金净额 = Column(Float)
    保单红利支出 = Column(Float)
    分保费用 = Column(Float)
    营业税金及附加 = Column(Float)
    销售费用 = Column(Float)
    管理费用 = Column(Float)
    堪探费用 = Column(Float)
    财务费用 = Column(Float)
    研发费用 = Column(Float)
    资产减值损失 = Column(Float)
    加_公允价值变动净收益 = Column(Float)
    投资收益 = Column(Float)
    其中_对联营企业和合营企业的投资收益 = Column(Float)
    汇兑收益 = Column(Float)
    其他收入 = Column(Float)
    信用减值损失 = Column(Float)
    净敞口套期收益 = Column(Float)
    资产处置收益 = Column(Float)
    影响营业利润的其他科目 = Column(Float)
    营业利润 = Column(Float)
    加_补贴收入 = Column(Float)
    营业外收入 = Column(Float)
    其中_非流动资产处置利得 = Column(Float)
    减_营业外支出 = Column(Float)
    其中_非流动资产处置损失 = Column(Float)
    加_影响利润总额的其他科目 = Column(Float)
    利润总额 = Column(Float)
    减_所得税 = Column(Float)
    加_影响净利润的其他科目 = Column(Float)
    净利润 = Column(Float)
    持续经营净利润 = Column(Float(2))
    终止经营净利润 = Column(Float(2))
    归属于母公司所有者的净利润 = Column(Float)
    少数股东损益 = Column(Float)
    基本每股收益 = Column(Float)
    稀释每股收益 = Column(Float)
    其他综合收益 = Column(Float)
    综合收益总额 = Column(Float)
    其中_归属于母公司 = Column(Float)
    其中_归属于少数股东 = Column(Float)
    备注 = Column(Text)


class PeriodlyCashFlowStatement(Base):
    """8.3.3 个股报告期现金表"""

    证券代码 = Column(String(6), primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, index=True)
    开始日期 = Column(DateTime)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(BigInteger)
    合并类型 = Column(Text)
    报表来源编码 = Column(BigInteger)
    报表来源 = Column(Text)
    销售商品_提供劳务收到的现金 = Column(Float)
    收到的税费返还 = Column(Float)
    收到其他与经营活动有关的现金 = Column(Float)
    经营活动现金流入小计 = Column(Float)
    购买商品_接受劳务支付的现金 = Column(Float)
    支付给职工以及为职工支付的现金 = Column(Float)
    支付的各项税费 = Column(Float)
    支付其他与经营活动有关的现金 = Column(Float)
    经营活动现金流出小计 = Column(Float)
    经营活动产生的现金流量净额 = Column(Float)
    收回投资收到的现金 = Column(Float)
    取得投资收益收到的现金 = Column(Float)
    处置固定资产_无形资产和其他长期资产收回的现金净额 = Column(Float)
    处置子公司及其他营业单位收到的现金净额 = Column(Float)
    收到其他与投资活动有关的现金 = Column(Float)
    投资活动现金流入小计 = Column(Float)
    购建固定资产_无形资产和其他长期资产支付的现金 = Column(Float)
    投资支付的现金 = Column(Float)
    质押贷款净增加额 = Column(Float)
    取得子公司及其他营业单位支付的现金净额 = Column(Float)
    支付其他与投资活动有关的现金 = Column(Float)
    投资活动现金流出小计 = Column(Float)
    投资活动产生的现金流量净额 = Column(Float)
    吸收投资收到的现金 = Column(Float)
    取得借款收到的现金 = Column(Float)
    发行债券收到的现金 = Column(Float)
    收到其他与筹资活动有关的现金 = Column(Float)
    筹资活动现金流入小计 = Column(Float)
    偿还债务支付的现金 = Column(Float)
    分配股利_利润或偿付利息支付的现金 = Column(Float)
    支付其他与筹资活动有关的现金 = Column(Float)
    筹资活动现金流出小计 = Column(Float)
    筹资活动产生的现金流量净额 = Column(Float)
    汇率变动对现金的影响 = Column(Float)
    其他原因对现金的影响 = Column(Float)
    现金及现金等价物净增加额 = Column(Float)
    期初现金及现金等价物余额 = Column(Float)
    期末现金及现金等价物余额 = Column(Float)
    净利润 = Column(Float)
    加_资产减值准备 = Column(Float)
    固定资产折旧_油气资产折耗_生产性生物资产折旧 = Column(Float)
    无形资产摊销 = Column(Float)
    长期待摊费用摊销 = Column(Float)
    处置固定资产_无形资产和其他长期资产的损失 = Column(Float)
    固定资产报废损失 = Column(Float)
    公允价值变动损失 = Column(Float)
    财务费用 = Column(Float)
    投资损失 = Column(Float)
    递延所得税资产减少 = Column(Float)
    递延所得税负债增加 = Column(Float)
    存货的减少 = Column(Float)
    经营性应收项目的减少 = Column(Float)
    经营性应付项目的增加 = Column(Float)
    其他 = Column(Float)
    经营活动产生的现金流量净额2 = Column(Float)
    债务转为资本 = Column(Float)
    一年内到期的可转换公司债券 = Column(Float)
    融资租入固定资产 = Column(Float)
    现金的期末余额 = Column(Float)
    减_现金的期初余额 = Column(Float)
    加_现金等价物的期末余额 = Column(Float)
    减_现金等价物的期初余额 = Column(Float)
    加_其他原因对现金的影响2 = Column(Float)
    现金及现金等价物净增加额2 = Column(Float)
    客户存款和同业存放款项净增加额 = Column(Float)
    向中央银行借款净增加额 = Column(Float)
    向其他金融机构拆入资金净增加额 = Column(Float)
    收到原保险合同保费取得的现金 = Column(Float)
    收到再保险业务现金净额 = Column(Float)
    保户储金及投资款净增加额 = Column(Float)
    处置以公允价值计量且其变动计入当期损益的金融资产净增加额 = Column(Float)
    收取利息_手续费及佣金的现金 = Column(Float)
    拆入资金净增加额 = Column(Float)
    回购业务资金净增加额 = Column(Float)
    客户贷款及垫款净增加额 = Column(Float)
    存放中央银行和同业款项净增加额 = Column(Float)
    支付原保险合同赔付款项的现金 = Column(Float)
    支付利息_手续费及佣金的现金 = Column(Float)
    支付保单红利的现金 = Column(Float)
    其中_子公司吸收少数股东投资收到的现金 = Column(Float)
    其中_子公司支付给少数股东的股利_利润 = Column(Float)
    投资性房地产的折旧及摊销 = Column(Float)


class PeriodlyBalanceSheet2007(Base):
    """8.3.4 金融类资产负债表2007版"""

    证券代码 = Column(String(6), primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, index=True)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(BigInteger)
    合并类型 = Column(Text)
    报表来源编码 = Column(BigInteger)
    报表来源 = Column(Text)
    存放同业款项 = Column(BigInteger)
    货币资金 = Column(Float)
    其中_客户资金存款 = Column(Float)
    现金及存放中央银行款项 = Column(BigInteger)
    结算备付金 = Column(Float)
    其中_客户备付金 = Column(Float)
    贵金属 = Column(BigInteger)
    拆出资金 = Column(BigInteger)
    交易性金融资产 = Column(BigInteger)
    衍生金融资产 = Column(BigInteger)
    买入返售金融资产 = Column(BigInteger)
    应收款项 = Column(BigInteger)
    应收利息 = Column(BigInteger)
    应收保费 = Column(Float)
    应收代位追偿款 = Column(Float)
    应收分保帐款 = Column(Float)
    应收分保未到期责任准备金 = Column(Float)
    应收分保未决赔款准备金 = Column(Float)
    应收分保寿险责任准备金 = Column(Float)
    应收分保长期健康险责任准备金 = Column(Float)
    保户质押贷款 = Column(Float)
    定期存款 = Column(Float)
    发放贷款及垫款 = Column(BigInteger)
    存出保证金 = Column(Float)
    代理业务资产 = Column(Float)
    应收款项类投资 = Column(Float)
    预付款项 = Column(Float)
    可供出售金融资产 = Column(BigInteger)
    持有至到期投资 = Column(BigInteger)
    长期股权投资 = Column(Float)
    贷款及应收款类金融资产 = Column(Float)
    存出资本保证金 = Column(Float)
    投资性房地产 = Column(BigInteger)
    存货 = Column(Float)
    固定资产 = Column(BigInteger)
    在建工程 = Column(Float)
    无形资产 = Column(BigInteger)
    其中_交易席位费 = Column(Float)
    商誉 = Column(BigInteger)
    长期待摊费用 = Column(Float)
    固定资产清理 = Column(Float)
    独立帐户资产 = Column(Float)
    递延所得税资产 = Column(BigInteger)
    其他资产 = Column(BigInteger)
    资产总计 = Column(BigInteger)
    向中央银行借款 = Column(BigInteger)
    同业及其他金融机构存放款项 = Column(BigInteger)
    短期借款 = Column(Float)
    其中_质押借款 = Column(Float)
    拆入资金 = Column(BigInteger)
    交易性金融负债 = Column(BigInteger)
    衍生金融负债 = Column(BigInteger)
    卖出回购金融资产款 = Column(BigInteger)
    吸收存款 = Column(BigInteger)
    代理买卖证券款 = Column(Float)
    代理承销证券款 = Column(Float)
    应付帐款 = Column(Float)
    应付票据 = Column(Float)
    预收款项 = Column(Float)
    预收保费 = Column(Float)
    应付手续费及佣金 = Column(Float)
    应付分保帐款 = Column(Float)
    应付职工薪酬 = Column(BigInteger)
    应交税费 = Column(BigInteger)
    应付利息 = Column(BigInteger)
    代理业务负债 = Column(Float)
    应付短期融资款 = Column(Float)
    应付款项 = Column(Float)
    预计负债 = Column(BigInteger)
    应付赔付款 = Column(Float)
    应付保单红利 = Column(Float)
    保户储金及投资款 = Column(Float)
    未到期责任准备金 = Column(Float)
    未决赔款准备金 = Column(Float)
    寿险责任准备金 = Column(Float)
    长期健康险责任准备金 = Column(Float)
    长期借款 = Column(Float)
    应付债券 = Column(BigInteger)
    其中_优先股_负债 = Column(Float)
    独立帐户负债 = Column(Float)
    递延所得税负债 = Column(Float)
    其他负债 = Column(BigInteger)
    负债合计 = Column(BigInteger)
    实收资本或股本 = Column(BigInteger)
    其他权益工具 = Column(BigInteger)
    其中_优先股_权益 = Column(BigInteger)
    永续债_权益 = Column(Float)
    资本公积 = Column(BigInteger)
    减_库存股 = Column(Float)
    其他综合收益 = Column(BigInteger)
    盈余公积 = Column(BigInteger)
    一般风险准备 = Column(BigInteger)
    未分配利润 = Column(BigInteger)
    外币报表折算差额 = Column(Float)
    归属于母公司所有者权益 = Column(BigInteger)
    少数股东权益 = Column(Float)
    所有者权益或股东权益合计 = Column(BigInteger)
    负债和所有者权益或股东权益总计 = Column(BigInteger)


class PeriodlyIncomeStatement2007(Base):
    """8.3.5 金融类利润表2007版"""

    证券代码 = Column(String(6), primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, index=True)
    开始日期 = Column(DateTime)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(BigInteger)
    合并类型 = Column(Text)
    报表来源编码 = Column(BigInteger)
    报表来源 = Column(Text)
    营业收入 = Column(Float)
    利息净收入 = Column(Float)
    其中_利息收入 = Column(Float)
    其中_利息支出 = Column(Float)
    手续费及佣金净收入 = Column(Float)
    其中_手续费及佣金收入 = Column(Float)
    其中_手续费及佣金支出 = Column(Float)
    其中_代理买卖证券业务净收入 = Column(Float)
    其中_证券承销业务净收入 = Column(Float)
    其中_委托客户管理资产业务净收入 = Column(Float)
    已赚保费 = Column(Float)
    保险业务收入 = Column(Float)
    其中_分保费收入 = Column(Float)
    减_分出保费 = Column(Float)
    提取未到期责任准备金 = Column(Float)
    投资收益 = Column(Float)
    其中_对联营企业和合营企业的投资收益 = Column(Float)
    公允价值变动收益 = Column(Float)
    汇兑收益 = Column(Float)
    其他业务收入 = Column(Float)
    营业支出 = Column(Float)
    退保金 = Column(Float)
    赔付支出 = Column(Float)
    减_摊回赔付支出 = Column(Float)
    提取保险责任准备金 = Column(Float)
    减_摊回保险责任准备金 = Column(Float)
    保单红利支出 = Column(Float)
    分保费用 = Column(Float)
    营业税金及附加 = Column(Float)
    手续费及佣金支出2 = Column(Float)
    业务及管理费 = Column(Float)
    减_摊回分保费用 = Column(Float)
    资产减值损失 = Column(Float)
    其他业务成本 = Column(Float)
    营业利润 = Column(Float)
    加_补贴收入 = Column(Float)
    营业外收入 = Column(Float)
    减_营业外支出 = Column(Float)
    加_影响利润总额的其他科目 = Column(Float)
    利润总额 = Column(Float)
    减_所得税 = Column(Float)
    加_影响净利润的其他科目 = Column(Float)
    净利润 = Column(Float)
    归属于母公司所有者的净利润 = Column(Float)
    少数股东损益 = Column(Float)
    基本每股收益 = Column(Float)
    稀释每股收益 = Column(Float)
    其他综合收益 = Column(Float)
    综合收益总额 = Column(Float)
    其中_归属于母公司 = Column(Float)
    其中_归属于少数股东 = Column(Float)
    其他收益 = Column(Float)


class PeriodlyCashFlowStatement2007(Base):
    """8.3.6 金融类现金流量表2007版"""

    证券代码 = Column(String(6), primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    公告日期 = Column(DateTime, index=True)
    开始日期 = Column(DateTime)
    截止日期 = Column(DateTime)
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    合并类型编码 = Column(BigInteger)
    合并类型 = Column(Text)
    报表来源编码 = Column(BigInteger)
    报表来源 = Column(Text)
    客户贷款及垫款净减少额 = Column(Float)
    客户存款和同业存放款项净增加额 = Column(Float)
    向中央银行借款净增加额 = Column(BigInteger)
    存放中央银行和同业款项净减少额 = Column(Float)
    向其他金融机构拆入资金净增加额 = Column(Float)
    收取利息_手续费及佣金的现金 = Column(BigInteger)
    处置交易性金融资产净增加额 = Column(Float)
    拆入资金净增加额 = Column(Float)
    回购业务资金净增加额 = Column(Float)
    销售商品_提供劳务收到的现金 = Column(Float)
    收到的税费返还 = Column(Float)
    收到原保险合同保费取得的现金 = Column(Float)
    收到再保业务现金净额 = Column(Float)
    保户储金及投资款净增加额 = Column(Float)
    收到其他与经营活动有关的现金 = Column(BigInteger)
    经营活动现金流入小计 = Column(BigInteger)
    客户贷款及垫款净增加额 = Column(BigInteger)
    客户存放及同业存放款项净减少额 = Column(Float)
    存放中央银行和同业款项净增加额 = Column(Float)
    向中央银行借款净减少额 = Column(Float)
    向其他金融机构拆出资金净增加额 = Column(Float)
    购入交易性金融资产净增加额 = Column(Float)
    回购业务资金净减少额 = Column(Float)
    支付利息_手续费及佣金的现金 = Column(BigInteger)
    购买商品_提供劳务支付的现金 = Column(Float)
    支付再保业务现金净额 = Column(Float)
    保户储金及投资款净减少额 = Column(Float)
    支付原保险合同赔付款项的现金 = Column(Float)
    支付保单红利的现金 = Column(Float)
    支付给职工以及为职工支付的现金 = Column(BigInteger)
    支付的各项税费 = Column(BigInteger)
    支付其他与经营活动有关的现金 = Column(BigInteger)
    经营活动现金流出小计 = Column(BigInteger)
    经营活动产生的现金流量净额 = Column(BigInteger)
    收回投资收到的现金 = Column(BigInteger)
    取得投资收益收到的现金 = Column(BigInteger)
    收到其他与投资活动有关的现金 = Column(Float)
    处置固定资产_无形资产和其他长期资产所收回的现金 = Column(Float)
    投资活动现金流入小计 = Column(BigInteger)
    投资支付的现金 = Column(BigInteger)
    质押贷款净增加额 = Column(Float)
    购建固定资产_无形资产和其他长期资产支付的现金 = Column(BigInteger)
    支付其他与投资活动有关的现金 = Column(Float)
    投资活动现金流出小计 = Column(BigInteger)
    投资活动产生的现金流量净额 = Column(BigInteger)
    吸收投资收到的现金 = Column(Float)
    发行债券收到的现金 = Column(BigInteger)
    取得借款收到的现金 = Column(Float)
    收到其他与筹资活动有关的现金 = Column(Float)
    筹资活动现金流入小计 = Column(BigInteger)
    偿还债务支付的现金 = Column(BigInteger)
    分配股利_利润或偿付利息支付的现金 = Column(BigInteger)
    支付其他与筹资活动有关的现金 = Column(Float)
    筹资活动现金流出小计 = Column(BigInteger)
    筹资活动产生的现金流量净额 = Column(BigInteger)
    汇率变动对现金的影响 = Column(BigInteger)
    其他原因对现金的影响 = Column(Float)
    现金及现金等价物净增加额 = Column(BigInteger)
    期初现金及现金等价物余额 = Column(BigInteger)
    期末现金及现金等价物余额 = Column(BigInteger)
    净利润 = Column(Float)
    加_资产减值准备 = Column(Float)
    固定资产折旧_油气资产折耗_生产性生物资产折旧 = Column(Float)
    无形资产摊销 = Column(Float)
    长期待摊费用摊销 = Column(Float)
    处置固定资产_无形资产和其他长期资产的损失 = Column(Float)
    固定资产报废损失 = Column(Float)
    公允价值变动损失 = Column(Float)
    财务费用 = Column(Float)
    投资损失 = Column(Float)
    递延所得税资产减少 = Column(Float)
    递延所得税负债增加 = Column(Float)
    存货的减少 = Column(Float)
    经营性应收项目的减少 = Column(Float)
    经营性应付项目的增加 = Column(Float)
    其他 = Column(Float)
    经营活动产生的现金流量净额2 = Column(Float)
    债务转为资本 = Column(Float)
    一年内到期的可转换公司债券 = Column(Float)
    融资租入固定资产 = Column(Float)
    现金及现金等价物净变动情况 = Column(Float)
    现金的期末余额 = Column(Float)
    减_现金的期初余额 = Column(Float)
    加_现金等价物的期末余额 = Column(Float)
    减_现金等价物的期初余额 = Column(Float)
    加_其他原因对现金的影响2 = Column(Float)
    现金及现金等价物净增加额 = Column(Float)
    投资性房地产的折旧及摊销 = Column(Float)


class PeriodlyFinancialIndicator(Base):
    """8.4.1 个股报告期指标表"""

    证券代码 = Column(String(6), primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    报告年度 = Column(DateTime, primary_key=True, nullable=False)
    机构名称 = Column(Text)
    开始日期 = Column(DateTime)
    截止日期 = Column(DateTime)
    数据来源编码 = Column(BigInteger)
    数据来源 = Column(Text, primary_key=True, nullable=False)
    每股收益 = Column(Float)
    基本每股收益 = Column(Float)
    稀释每股收益 = Column(Float)
    扣除非经常性损益每股收益 = Column(Float)
    每股未分配利润 = Column(Float)
    每股净资产 = Column(Float)
    调整后每股净资产 = Column(Float)
    每股资本公积金 = Column(Float)
    营业利润率 = Column(Float)
    营业税金率 = Column(Float)
    营业成本率 = Column(Float)
    净资产收益率 = Column(Float)
    投资收益率 = Column(Float)
    总资产报酬率 = Column(Float)
    净利润率 = Column(Float)
    管理费用率 = Column(Float)
    财务费用率 = Column(Float)
    成本费用利润率 = Column(Float)
    三费比重 = Column(Float)
    应收账款周转率 = Column(Float)
    存货周转率 = Column(Float)
    运营资金周转率 = Column(Float)
    总资产周转率 = Column(Float)
    固定资产周转率 = Column(Float)
    应收账款周转天数 = Column(Float)
    存货周转天数 = Column(Float)
    流动资产周转率 = Column(Float)
    流动资产周转天数 = Column(Float)
    总资产周转天数 = Column(Float)
    股东权益周转率 = Column(Float)
    流动资产比率 = Column(Float)
    货币资金比率 = Column(Float)
    交易性金融资产比率 = Column(Float)
    存货比率 = Column(Float)
    固定资产比率 = Column(Float)
    负债结构比 = Column(Float)
    产权比率 = Column(Float)
    净资产比率 = Column(Float)
    资产负债比率 = Column(Float)
    流动比率 = Column(Float)
    速动比率 = Column(Float)
    现金比率 = Column(Float)
    利息保障倍数 = Column(Float)
    营运资金 = Column(Float)
    非流动负债比率 = Column(Float)
    流动负债比率 = Column(Float)
    保守速动比率 = Column(Float)
    现金到期债务比率 = Column(Float)
    有形资产净值债务率 = Column(Float)
    营业收入增长率 = Column(Float)
    净利润增长率 = Column(Float)
    净资产增长率 = Column(Float)
    固定资产增长率 = Column(Float)
    总资产增长率 = Column(Float)
    投资收益增长率 = Column(Float)
    营业利润增长率 = Column(Float)
    每股现金流量 = Column(Float)
    每股经营现金流量 = Column(Float)
    经营净现金比率_短期债务 = Column(Float)
    经营净现金比率_全部债务 = Column(Float)
    经营活动现金净流量与净利润比率 = Column(Float)
    营业收入现金含量 = Column(Float)
    全部资产现金回收率 = Column(Float)
    净资产收益率_扣除非经常性损益 = Column(Float)
    净资产收益率_加权 = Column(Float)
    净资产收益率_加权_扣除非经常性损益 = Column(Float)
    合并类型编码 = Column(BigInteger)
    合并类型 = Column(Text)
    扣除非经常性损益后的净利润 = Column(Float)
    非经常性损益合计 = Column(Float)
    毛利率 = Column(Float)
    期间费用率 = Column(Float)
    现金转换周期 = Column(Float)
    净资产收益率_1 = Column(Float)
    净利含金量 = Column(Float)
    非经常性损益占比 = Column(Float)
    期间费用增长率 = Column(Float)
    基本获利能力 = Column(Float)
    应收账款占比 = Column(Float)
    存货占比 = Column(Float)
    年化期间费用毛利比 = Column(Float)


class FinancialIndicatorRanking(Base):
    """8.4.2 财务指标行业排名"""
    证券代码 = Column(String(6), primary_key=True, nullable=False, index=True)
    证券简称 = Column(String(10))
    行业ID = Column(Text)
    行业名称 = Column(Text)
    行业级别 = Column(BigInteger)
    级别说明 = Column(Text)
    报告期 = Column(DateTime, primary_key=True, nullable=False)
    每股收益 = Column(Float)
    每股收益_行业均值 = Column(Float)
    每股收益_行业排名 = Column(BigInteger)
    扣除后每股收益 = Column(Float)
    扣除后每股收益_行业均值 = Column(Float)
    扣除后每股收益_行业排名 = Column(BigInteger)
    每股净资产 = Column(Float)
    每股净资产_行业均值 = Column(Float)
    每股净资产_行业排名 = Column(BigInteger)
    净资产收益率 = Column(Float)
    净资产收益率_行业均值 = Column(Float)
    净资产收益率_行业排名 = Column(BigInteger)
    每股未分配利润 = Column(Float)
    每股未分配利润_行业均值 = Column(Float)
    每股未分配利润_行业排名 = Column(BigInteger)
    每股经营现金流量 = Column(Float)
    每股经营现金流量_行业均值 = Column(Float)
    每股经营现金流量_行业排名 = Column(BigInteger)
    营业收入增长率 = Column(Float)
    营业收入增长率_行业均值 = Column(Float)
    营业收入增长率_行业排名 = Column(Float)
    净利润增长率 = Column(Float)
    净利润增长率_行业均值 = Column(Float)
    净利润增长率_行业排名 = Column(Float)
    毛利率 = Column(Float)
    毛利率_行业均值 = Column(Float)
    毛利率_行业排名 = Column(Float)
    资产负债率 = Column(Float)
    资产负债率_行业均值 = Column(Float)
    资产负债率_行业排名 = Column(BigInteger)
    应收帐款周转率 = Column(Float)
    应收帐款周转率_行业均值 = Column(Float)
    应收帐款周转率_行业排名 = Column(Float)


class StockInfo(Base):
    """1.1 基本资料"""
    证券代码 = Column(String(6), primary_key=True, index=True)
    证券简称 = Column(String(10))
    机构名称 = Column(Text)
    股票类别 = Column(Text)
    上市日期 = Column(DateTime)
    上市地点 = Column(Text)
    上市状态 = Column(Text)
    摘牌日期 = Column(DateTime)
    ISIN代码 = Column(Text)
    英文名称 = Column(Text)
    英文简称 = Column(Text)
    成立日期 = Column(DateTime)
    注册资本 = Column(Float)
    法定代表人 = Column(Text)
    主营业务 = Column(Text)
    经营范围 = Column(Text)
    公司简介 = Column(Text)
    省份 = Column(Text)
    城市 = Column(Text)
    注册地址 = Column(Text)
    办公地址 = Column(Text)
    邮编 = Column(BigInteger)
    公司电话 = Column(Text)
    公司传真 = Column(Text)
    公司电子邮件地址 = Column(Text)
    公司网站 = Column(Text)
    证监会一级行业名称 = Column(Text)
    证监会二级行业名称 = Column(Text)
    申万行业一级名称 = Column(Text)
    申万行业二级名称 = Column(Text)
    申万行业三级名称 = Column(Text)
    董事长 = Column(Text)
    独立董事 = Column(Text)
    总经理 = Column(Text)
    董事会秘书 = Column(Text)
    董秘电话 = Column(Text)
    董秘传真 = Column(Text)
    董秘邮箱 = Column(Text)
    证券事务代表 = Column(Text)
    会计师事务所 = Column(Text)
    律师事务所 = Column(Text)