from cnswd.constants import MARKET_START

from cnswd.sql.ts import (
    BigDeal,
    Margin,
    Deregulation,
    Underweight,
    Overweight,
    Equity,
    ExecutiveShareholdings,
    ActualController,
    Concentration,
    PerformanceForecast,
    PrimaryIndicator,
    Bond,
    Raise,
    Placement,
    Ipo,
    Proposed,
    Suspend,
    Delisted,
    IPOAudit,
    Reorganization,
    DebtRestructuring,
    Merger,
    ShareVariation,
    Litigation,
    Colla,
    Pe,
    Rnav,
    StockRating,
)


MODEL_MAPS = {
    '1.1':     BigDeal,
    '2.1':     Margin,
    '3.1':     Deregulation,
    '4.1':     Underweight,
    '4.2':     Overweight,
    '5.1':     Equity,
    # '5.3':     ExecutiveShareholdings, # 数据逻辑错误，暂不使用
    '5.4':     ActualController,
    '5.5':     Concentration,
    '6.1':     PerformanceForecast,
    '7.1':     PrimaryIndicator,
    '11.1':    Bond,
    '11.2':    Raise,
    '11.3':    Placement,
    '11.4':    Ipo,
    '12.1':    Proposed,
    '12.2':    Suspend,
    '12.3':    Delisted,
    '13.1':    IPOAudit,
    '13.2':    Reorganization,
    '13.3':    DebtRestructuring,
    '13.4':    Merger,
    '13.5':    ShareVariation,
    '13.6':    Litigation,
    '13.7':    Colla,
    '14.1':    Pe,
    '15.1':    Rnav,
    '16.1':    StockRating,
}
default_start_date = MARKET_START.tz_localize(None).strftime(r'%Y-%m-%d')
# 日期字段名称 frequency 开始日期
DATE_MAPS = {
    '1.1':     ('交易日期', 'B', '2002-03-19'),
    '2.1':     ('交易日期', 'B', '2010-03-31'),
    '3.1':     ('实际解除限售日期', 'B', '2007-09-14'),
    '4.1':     ('公告日期', 'B', '2007-09-12'),
    '4.2':     ('公告日期', 'B', '2007-09-12'),
    '5.1':     ('公告日期', None, default_start_date),
    # '5.3':     ('公告日期', 'B', '2004-11-29'),          # 数据逻辑错误，暂不使用
    '5.4':     ('变动日期', None, default_start_date),
    '5.5':     ('变动日期', 'Q', '2001-09-30'),
    '6.1':     ('报告年度', 'Q', '2002-03-31'),
    '7.1':     ('报告期', 'Q', '2000-06-30'),
    '11.1':    ('发行起始日', 'B', '1992-11-19'),
    '11.2':    ('发行日期', 'B', '1998-06-24'),
    '11.3':    ('配股日期', 'B', default_start_date),
    '11.4':    ('上市日期', 'B', default_start_date),
    '12.1':    (None, None),
    '12.2':    (None, None),
    '12.3':    (None, None),
    '13.1':    ('公告日期', 'B', default_start_date),
    '13.2':    ('公告日期', 'B', default_start_date),
    '13.3':    ('公告日期', 'B', default_start_date),
    '13.4':    ('公告日期', 'B', default_start_date),
    '13.5':    ('公告日期', 'B', default_start_date),
    '13.6':    ('公告日期', 'B', default_start_date),
    '13.7':    ('公告日期', 'B', default_start_date),
    '14.1':    ('变动日期', 'B', default_start_date),
    '15.1':    ('净值日期', 'B', default_start_date),
    '16.1':    ('发布日期', 'B', default_start_date),
}
